In [27]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_absolute_error, r2_score,accuracy_score, mean_squared_error
from sklearn.ensemble import RandomForestRegressor
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
import pickle
df = pd.read_csv("C:\\Users\\pawan\\Downloads\\EnvironmentProject\\ML\\co2-emissions-per-capita.csv")
df.tail()

         Entity Code  Year  CO₂ emissions per capita
26504  Zimbabwe  ZWE  2020                  0.546847
26505  Zimbabwe  ZWE  2021                  0.647125
26506  Zimbabwe  ZWE  2022                  0.761205
26507  Zimbabwe  ZWE  2023                  0.822681
26508  Zimbabwe  ZWE  2024                  0.823666

In [3]:
df = pd.read_csv("C:\\Users\\pawan\\Downloads\\EnvironmentProject\\ML\\annual-freshwater-withdrawals.csv")
remove_entities = ["World","Asia (excl. China and India)","Europe","Low-income countries","Europe (excl. EU-27)",
                   "Europe (excl. EU-28)","European Union (27)","Lower-middle-income countries","North America",
                    "North America (excl. USA)","European Union (28)","High-income countries","Upper-middle-income countries","Asia",
                  "Europe and Central Asia (WB)","East Asia and Pacific (WB)","European Union (27)"," Afghanistan and Pakistan (WB)","South Asia (WB)"]
df = df[~df["Entity"].isin(remove_entities)]
#df["Entity"].unique()
X = df[["Entity","Year"]]
y = df["Annual freshwater withdrawals"]
train = df[df["Year"] <= 2018]
test = df[df["Year"] > 2018]
X_train = train[["Entity", "Year"]]
y_train = train["Annual freshwater withdrawals"]

X_test = test[["Entity", "Year"]]
y_test = test["Annual freshwater withdrawals"]
preprocessor = ColumnTransformer(
    transformers=[("country",OneHotEncoder(handle_unknown="ignore"), ["Entity"])],
    remainder="passthrough"
)
Water_model = Pipeline(steps=[("preprocessor", preprocessor),("regressor", RandomForestRegressor(random_state=42))]
)
Water_model.fit(X_train, y_train)
predictions = Water_model.predict(X_test)
print("Actual minimum:", y_test.min())
print("Actual maximum:", y_test.max())
print("Actual mean:", y_test.mean())

print("MAE:", mean_absolute_error(y_test, predictions))
mean_actual = y_test.mean()
print("MAE %:", (mae / mean_actual) * 100)
print("R²:", r2_score(y_test, predictions))

Actual minimum: 4400000.0
Actual maximum: 647500000000.0
Actual mean: 28954554478.390244
MAE: 660770837.1517615

NameError: name 'mae' is not defined

In [4]:
df = pd.read_csv("C:\\Users\\pawan\\Downloads\\EnvironmentProject\\ML\\outdoor-air-pollution-exposure.csv")
remove_entities = ["World","Asia (excl. China and India)","Europe","Low-income countries","Europe (excl. EU-27)",
                   "Europe (excl. EU-28)","European Union (27)","Lower-middle-income countries","North America",
                    "North America (excl. USA)","European Union (28)","High-income countries","Upper-middle-income countries","Asia"]
df = df[~df["Entity"].isin(remove_entities)]
#df["Entity"].unique()
X = df[["Entity","Year"]]
y = df["Outdoor air pollution exposure (population-weighted PM2.5)"]
train = df[df["Year"] <= 2018]
test = df[df["Year"] > 2018]
X_train = train[["Entity", "Year"]]
y_train = train["Outdoor air pollution exposure (population-weighted PM2.5)"]

X_test = test[["Entity", "Year"]]
y_test = test["Outdoor air pollution exposure (population-weighted PM2.5)"]
preprocessor = ColumnTransformer(
    transformers=[("country",OneHotEncoder(handle_unknown="ignore"), ["Entity"])],
    remainder="passthrough"
)
Air_pollution_model = Pipeline(steps=[("preprocessor", preprocessor),("regressor", RandomForestRegressor(random_state=42))]
)
Air_pollution_model.fit(X_train, y_train)
predictions = Air_pollution_model.predict(X_test)
print("MAE :", mean_absolute_error(y_test, predictions))
print("R² :", r2_score(y_test, predictions))

MAE : 1.6318244488933875
R² : 0.9648946759639448

In [5]:
df = pd.read_csv("C:\\Users\\pawan\\Downloads\\EnvironmentProject\\ML\\annual-change-forest-area.csv")
df.head()
remove_entities = ["World","Asia (excl. China and India)","Europe","Low-income countries","Europe (excl. EU-27)",
                   "Europe (excl. EU-28)","European Union (27)","Lower-middle-income countries","North America",
                    "North America (excl. USA)","European Union (28)","High-income countries","Upper-middle-income countries"]
df = df[~df["Entity"].isin(remove_entities)]
X = df[["Entity","Year"]]
y = df["Annual change in forest area"]
train = df[df["Year"] <= 2018]
test = test = df[df["Year"] > 2018]
X_train = train[["Entity", "Year"]]
y_train = train["Annual change in forest area"]

X_test = test[["Entity", "Year"]]
y_test = test["Annual change in forest area"]
preprocessor = ColumnTransformer(
    transformers=[
        ("country",OneHotEncoder(handle_unknown="ignore"), ["Entity"]
        )
    ],
    remainder="passthrough"
)
forest_model = Pipeline(
    steps=[("preprocessor", preprocessor),("regressor", RandomForestRegressor(random_state=42))
    ]
)
forest_model.fit(X_train, y_train)
predictions = forest_model.predict(X_test)
print("MAE :", mean_absolute_error(y_test, predictions))
print("R² :", r2_score(y_test, predictions))

MAE : 15748.85287436508
R² : 0.9694985076241132

In [ ]:
# PM2.5
with open("pm25_model.pkl", "wb") as f:
    pickle.dump(Air_pollution_model, f)

# Water Withdrawal
with open("water_withdrawal_model.pkl", "wb") as f:
    pickle.dump(Water_model, f)
#forest model
with open("forest_changing_model.pkl","wb")as f:
    pickle.dump(forest_model, f)

In [9]:
df = pd.read_csv("C:\\Users\\pawan\\Downloads\\EnvironmentProject\\ML\\co2-emissions-per-capita.csv")
df.head()

        Entity Code  Year  CO₂ emissions per capita
0  Afghanistan  AFG  1949                  0.001992
1  Afghanistan  AFG  1950                  0.010837
2  Afghanistan  AFG  1951                  0.011625
3  Afghanistan  AFG  1952                  0.011468
4  Afghanistan  AFG  1953                  0.013123

In [8]:
df = pd.read_csv("C:\\Users\\pawan\\Downloads\\EnvironmentProject\\ML\\co2-emissions-per-capita.csv")
df.head()
remove_entities = ["World","Asia (excl. China and India)","Europe","Low-income countries","Europe (excl. EU-27)",
                   "Europe (excl. EU-28)","European Union (27)","Lower-middle-income countries","North America",
                    "North America (excl. USA)","European Union (28)","High-income countries","Upper-middle-income countries"]
df = df[~df["Entity"].isin(remove_entities)]
X = df[["Entity","Year"]]
y = df["CO₂ emissions per capita"]
train = df[df["Year"] <= 2018]
test = df[df["Year"] > 2018]
X_train = train[["Entity", "Year"]]
y_train = train["CO₂ emissions per capita"]

X_test = test[["Entity", "Year"]]
y_test = test["CO₂ emissions per capita"]
preprocessor = ColumnTransformer(
    transformers=[
        (
            "country",
            OneHotEncoder(handle_unknown="ignore"),
            ["Entity"]
        )
    ],
    remainder="passthrough"
)
Climate_model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("regressor", RandomForestRegressor(
            random_state=42
        ))
    ]
)
Climate_model.fit(X_train, y_train)
predictions = Climate_model.predict(X_test)
print("MAE :", mean_absolute_error(y_test, predictions))
print("R² :", r2_score(y_test, predictions))

MAE : 0.5932027277927676
R² : 0.9284209863059109

In [13]:
with open("pm25_model.pkl", "wb") as f:
    pickle.dump(Air_pollution_model, f)

# Water Withdrawal
with open("water_withdrawal_model.pkl", "wb") as f:
    pickle.dump(Water_model, f)
#forest model
with open("forest_changing_model.pkl","wb")as f:
    pickle.dump(forest_model, f)

#climate model
with open("climate_change_model.pkl","wb")as f:
    pickle.dump(Climate_model, f)
    print("Model saved")

Model saved

In [18]:
import pickle
import pandas as pd
import json

# Countries for which we want future predictions
target_countries = [
  "Australia",
    "Bangladesh",
    "Brazil",
    "China",
    "Egypt",
    "Germany",
    "India",
    "Japan",
    "Kenya",
    "Kuwait",
    "Pakistan",
    "Sweden",
    "Uganda",
    "United Kingdom",
    "United States"
]

# Years we want predictions for
future_years = [2025, 2026, 2027,2028,2029,2030]


# Create input data
future_rows = []

for country in target_countries:
    for year in future_years:
        future_rows.append({
            "Entity": country,
            "Year": year
        })

X_future = pd.DataFrame(future_rows)
models = {
    "climate_change_model.pkl": "co2_predictions.json",
    "pm25_model.pkl": "pm25_predictions.json",
    "water_withdrawal_model.pkl": "water_predictions.json",
    "forest_changing_model.pkl": "forest_predictions.json"
}

print(X_future)
print(models)

           Entity  Year
0       Australia  2025
1       Australia  2026
2       Australia  2027
3       Australia  2028
4       Australia  2029
..            ...   ...
85  United States  2026
86  United States  2027
87  United States  2028
88  United States  2029
89  United States  2030

[90 rows x 2 columns]
{'climate_change_model.pkl': 'co2_predictions.json', 'pm25_model.pkl': 'pm25_predictions.json', 'water_withdrawal_model.pkl': 'water_predictions.json', 'forest_changing_model.pkl': 'forest_predictions.json'}

In [19]:
for model_file, output_file in models.items():

    # Load the saved model
    with open(model_file, "rb") as f:
        model = pickle.load(f)

    # Make predictions
    predictions = model.predict(X_future)

    # Copy country/year data
    result = X_future.copy()

    # Add prediction
    result["value"] = predictions

    print(model_file)
    print(result)

climate_change_model.pkl
           Entity  Year      value
0       Australia  2025  16.612302
1       Australia  2026  16.612302
2       Australia  2027  16.612302
3       Australia  2028  16.612302
4       Australia  2029  16.612302
..            ...   ...        ...
85  United States  2026  15.941045
86  United States  2027  15.941045
87  United States  2028  15.941045
88  United States  2029  15.941045
89  United States  2030  15.941045

[90 rows x 3 columns]
pm25_model.pkl
           Entity  Year  value
0       Australia  2025  5.858
1       Australia  2026  5.858
2       Australia  2027  5.858
3       Australia  2028  5.858
4       Australia  2029  5.858
..            ...   ...    ...
85  United States  2026  7.854
86  United States  2027  7.854
87  United States  2028  7.854
88  United States  2029  7.854
89  United States  2030  7.854

[90 rows x 3 columns]
water_withdrawal_model.pkl
           Entity  Year         value
0       Australia  2025  1.216351e+10
1       Australia  2026  1.216351e+10
2       Australia  2027  1.216351e+10
3       Australia  2028  1.216351e+10
4       Australia  2029  1.216351e+10
..            ...   ...           ...
85  United States  2026  4.439841e+11
86  United States  2027  4.439841e+11
87  United States  2028  4.439841e+11
88  United States  2029  4.439841e+11
89  United States  2030  4.439841e+11

[90 rows x 3 columns]
forest_changing_model.pkl
           Entity  Year        value
0       Australia  2025  158932.9424
1       Australia  2026  158932.9424
2       Australia  2027  158932.9424
3       Australia  2028  158932.9424
4       Australia  2029  158932.9424
..            ...   ...          ...
85  United States  2026 -168000.0000
86  United States  2027 -168000.0000
87  United States  2028 -168000.0000
88  United States  2029 -168000.0000
89  United States  2030 -168000.0000

[90 rows x 3 columns]

In [20]:
## AIR POLLUTION
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score
df = pd.read_csv("C:\\Users\\pawan\\Downloads\\EnvironmentProject\\ML\\outdoor-air-pollution-exposure.csv")
target = "Outdoor air pollution exposure (population-weighted PM2.5)"

train = df[df["Year"] <= 2018]
test = df[df["Year"] > 2018]
countries = [
    "Australia",
    "Bangladesh",
    "Brazil",
    "China",
    "Egypt",
    "Germany",
    "India",
    "Japan",
    "Kenya",
    "Kuwait",
    "Pakistan",
    "Sweden",
    "Uganda",
    "United Kingdom",
    "United States"
]
linear_models = {}

for country in countries:

    country_train = train[train["Entity"] == country]

    X = country_train[["Year"]]
    y = country_train[target]

    model = LinearRegression()

    model.fit(X, y)

    linear_models[country] = model

print("All country models trained successfully.")
test_predictions = []

for country in countries:

    country_test = test[test["Entity"] == country]

    if len(country_test) == 0:
        continue

    model = linear_models[country]

    predictions = model.predict(country_test[["Year"]])

    for actual, predicted in zip(
        country_test[target],
        predictions
    ):
        test_predictions.append({
            "Entity": country,
            "Actual": actual,
            "Predicted": predicted
        })
results = pd.DataFrame(test_predictions)
print(results.head())
mae = mean_absolute_error(
    results["Actual"],
    results["Predicted"]
)

r2 = r2_score(
    results["Actual"],
    results["Predicted"]
)

print("Linear Regression MAE :", mae)
print("Linear Regression R² :", r2)

All country models trained successfully.
      Entity  Actual  Predicted
0  Australia     9.0   5.694762
1  Australia     6.7   5.708139
2  Australia     5.3   5.721515
3  Australia     5.1   5.734892
4  Australia     5.5   5.748268
Linear Regression MAE : 4.7778321308321265
Linear Regression R² : 0.8606842789441995

In [21]:
# AIR POLLUTION
future_years = [2025, 2026, 2027,2028,2029,2030]

future_rows = []

for country in countries:

    model = linear_models[country]

    for year in future_years:

        prediction = model.predict(
            pd.DataFrame({"Year": [year]})
        )[0]

        future_rows.append({
            "country": country,
            "year": year,
            "value": round(float(prediction), 2),
            "predicted": True
        })

future_predictions = pd.DataFrame(future_rows)

print(future_predictions)

          country  year  value  predicted
0       Australia  2025   5.78       True
1       Australia  2026   5.79       True
2       Australia  2027   5.80       True
3       Australia  2028   5.82       True
4       Australia  2029   5.83       True
..            ...   ...    ...        ...
85  United States  2026   4.98       True
86  United States  2027   4.68       True
87  United States  2028   4.39       True
88  United States  2029   4.09       True
89  United States  2030   3.80       True

[90 rows x 4 columns]

In [23]:
# WATER MODEL
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score
import pandas as pd

df = pd.read_csv("C:\\Users\\pawan\\Downloads\\EnvironmentProject\\ML\\annual-freshwater-withdrawals.csv")

target = "Annual freshwater withdrawals"

train = df[df["Year"] <= 2018]
test = df[df["Year"] > 2018]

countries = [
    "Australia",
    "Bangladesh",
    "Brazil",
    "China",
    "Egypt",
    "Germany",
    "India",
    "Japan",
    "Kenya",
    "Kuwait",
    "Pakistan",
    "Sweden",
    "Uganda",
    "United Kingdom",
    "United States"
]

linear_models = {}

for country in countries:

    country_train = train[train["Entity"] == country]

    X = country_train[["Year"]]
    y = country_train[target]

    model = LinearRegression()
    model.fit(X, y)

    linear_models[country] = model

print("All water models trained successfully.")
test_predictions = []

for country in countries:

    country_test = test[test["Entity"] == country]

    if len(country_test) == 0:
        continue

    model = linear_models[country]

    predictions = model.predict(country_test[["Year"]])

    for actual, predicted in zip(
        country_test[target],
        predictions
    ):
        test_predictions.append({
            "Entity": country,
            "Actual": actual,
            "Predicted": predicted
        })

results = pd.DataFrame(test_predictions)

mae = mean_absolute_error(
    results["Actual"],
    results["Predicted"]
)

r2 = r2_score(
    results["Actual"],
    results["Predicted"]
)

print("Water Linear Regression MAE :", mae)
print("Water Linear Regression R² :", r2)
#prediction
future_years = [2025, 2026, 2027,2028,2029,2030]

future_rows = []

for country in countries:

    model = linear_models[country]

    for year in future_years:

        prediction = model.predict(
            pd.DataFrame({"Year": [year]})
        )[0]

        future_rows.append({
            "country": country,
            "year": year,
            "value": round(float(prediction), 2),
            "predicted": True
        })

future_predictions = pd.DataFrame(future_rows)
print(future_predictions)

All water models trained successfully.
Water Linear Regression MAE : 10839931317.32613
Water Linear Regression R² : 0.9886792907366609
          country  year         value  predicted
0       Australia  2025  9.372466e+09       True
1       Australia  2026  8.952252e+09       True
2       Australia  2027  8.532038e+09       True
3       Australia  2028  8.111824e+09       True
4       Australia  2029  7.691610e+09       True
..            ...   ...           ...        ...
85  United States  2026  4.183975e+11       True
86  United States  2027  4.166074e+11       True
87  United States  2028  4.148172e+11       True
88  United States  2029  4.130271e+11       True
89  United States  2030  4.112369e+11       True

[90 rows x 4 columns]

In [26]:
# FOREST MODEL
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score
import pandas as pd

df = pd.read_csv("C:\\Users\\pawan\\Downloads\\EnvironmentProject\\ML\\annual-change-forest-area.csv")

target = "Annual change in forest area"

train = df[df["Year"] <= 2018]
test = df[df["Year"] > 2018]

countries = [
    "Australia",
    "Bangladesh",
    "Brazil",
    "China",
    "Egypt",
    "Germany",
    "India",
    "Japan",
    "Kenya",
    "Kuwait",
    "Pakistan",
    "Sweden",
    "Uganda",
    "United Kingdom",
    "United States"
]

linear_models = {}

for country in countries:

    country_train = train[train["Entity"] == country]

    X = country_train[["Year"]]
    y = country_train[target]

    model = LinearRegression()
    model.fit(X, y)

    linear_models[country] = model

print("All forest models trained successfully.")
test_predictions = []

for country in countries:

    country_test = test[test["Entity"] == country]

    if len(country_test) == 0:
        continue

    model = linear_models[country]

    predictions = model.predict(country_test[["Year"]])

    for actual, predicted in zip(
        country_test[target],
        predictions
    ):
        test_predictions.append({
            "Entity": country,
            "Actual": actual,
            "Predicted": predicted
        })

results = pd.DataFrame(test_predictions)

mae = mean_absolute_error(
    results["Actual"],
    results["Predicted"]
)

r2 = r2_score(
    results["Actual"],
    results["Predicted"]
)

print("Forest Linear Regression MAE :", mae)
print("Forest Linear Regression R² :", r2)
#prediction
future_years = [2025, 2026, 2027,2028,2029,2030]

future_rows = []

for country in countries:

    model = linear_models[country]

    for year in future_years:

        prediction = model.predict(
            pd.DataFrame({"Year": [year]})
        )[0]

        future_rows.append({
            "country": country,
            "year": year,
            "value": round(float(prediction), 2),
            "predicted": True
        })

future_predictions = pd.DataFrame(future_rows)
print(future_predictions)

All forest models trained successfully.
Forest Linear Regression MAE : 212538.60904275972
Forest Linear Regression R² : 0.6092771579707479
          country  year      value  predicted
0       Australia  2025  285263.97       True
1       Australia  2026  301961.48       True
2       Australia  2027  318658.98       True
3       Australia  2028  335356.48       True
4       Australia  2029  352053.98       True
..            ...   ...        ...        ...
85  United States  2026  264420.63       True
86  United States  2027  264857.14       True
87  United States  2028  265293.65       True
88  United States  2029  265730.16       True
89  United States  2030  266166.67       True

[90 rows x 4 columns]

In [28]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score
import pandas as pd

df = pd.read_csv("C:\\Users\\pawan\\Downloads\\EnvironmentProject\\ML\\co2-emissions-per-capita.csv")

target = "CO₂ emissions per capita"

train = df[df["Year"] <= 2018]
test = df[df["Year"] > 2018]

countries = [
    "Australia",
    "Bangladesh",
    "Brazil",
    "China",
    "Egypt",
    "Germany",
    "India",
    "Japan",
    "Kenya",
    "Kuwait",
    "Pakistan",
    "Sweden",
    "Uganda",
    "United Kingdom",
    "United States"
]

linear_models = {}

for country in countries:

    country_train = train[train["Entity"] == country]

    X = country_train[["Year"]]
    y = country_train[target]

    model = LinearRegression()
    model.fit(X, y)

    linear_models[country] = model

print("All climate models trained successfully.")
test_predictions = []

for country in countries:

    country_test = test[test["Entity"] == country]

    if len(country_test) == 0:
        continue

    model = linear_models[country]

    predictions = model.predict(country_test[["Year"]])

    for actual, predicted in zip(
        country_test[target],
        predictions
    ):
        test_predictions.append({
            "Entity": country,
            "Actual": actual,
            "Predicted": predicted
        })

results = pd.DataFrame(test_predictions)

mae = mean_absolute_error(
    results["Actual"],
    results["Predicted"]
)

r2 = r2_score(
    results["Actual"],
    results["Predicted"]
)

print("Climate Linear Regression MAE :", mae)
print("Climate Linear Regression R² :", r2)
#prediction
future_years = [2025, 2026, 2027,2028,2029,2030]

future_rows = []

for country in countries:

    model = linear_models[country]

    for year in future_years:

        prediction = model.predict(
            pd.DataFrame({"Year": [year]})
        )[0]

        future_rows.append({
            "country": country,
            "year": year,
            "value": round(float(prediction), 2),
            "predicted": True
        })

future_predictions = pd.DataFrame(future_rows)
print(future_predictions)

All climate models trained successfully.
Climate Linear Regression MAE : 3.2863649306573475
Climate Linear Regression R² : 0.33899211354942516
          country  year  value  predicted
0       Australia  2025  15.61       True
1       Australia  2026  15.69       True
2       Australia  2027  15.78       True
3       Australia  2028  15.86       True
4       Australia  2029  15.95       True
..            ...   ...    ...        ...
85  United States  2026  24.01       True
86  United States  2027  24.13       True
87  United States  2028  24.25       True
88  United States  2029  24.37       True
89  United States  2030  24.49       True

[90 rows x 4 columns]

In [39]:
import json
import pandas as pd
from sklearn.linear_model import LinearRegression

# 1. Updated Function (added allow_negative=False)
def train_and_export(df, entity_col, year_col, value_col, target_countries, future_years, output_file, min_year=2005, allow_negative=False):
    output = {}
    for country in target_countries:
        subset = df[df[entity_col] == country].sort_values(year_col)
        subset = subset[subset[year_col] >= min_year]

        if len(subset) < 5:
            continue

        X_train = subset[[year_col]]
        y_train = subset[value_col]

        model = LinearRegression()
        model.fit(X_train, y_train)

        X_future = pd.DataFrame({year_col: future_years})
        
        # Only clip to 0 if allow_negative is False
        preds = model.predict(X_future)
        if not allow_negative:
            preds = preds.clip(min=0)

        output[country] = [
            {"country": country, "year": int(y), "value": round(float(v), 2), "predicted": True}
            for y, v in zip(future_years, preds)
        ]

    with open(output_file, "w") as f:
        json.dump(output, f, indent=2)
    print(f"Exported {output_file}")

# 2. Make sure your variables are defined
target_countries = [
    "Australia", "Bangladesh", "Brazil", "China", "Egypt", 
    "Germany", "India", "Japan", "Kenya", "Kuwait", 
    "Pakistan", "Sweden", "Uganda", "United Kingdom", "United States"
]
future_years = [2025, 2026, 2027, 2028, 2029, 2030]

# (Assume co2_df, pm25_df, water_df, forest_df are already loaded via pd.read_csv here)
co2_df = pd.read_csv("C:\\Users\\pawan\\Downloads\\EnvironmentProject\\ML\\co2-emissions-per-capita.csv")
pm25_df = pd.read_csv("C:\\Users\\pawan\\Downloads\\EnvironmentProject\\ML\\outdoor-air-pollution-exposure.csv") # Apni PM2.5 file ka naam dalein
water_df = pd.read_csv("C:\\Users\\pawan\\Downloads\\EnvironmentProject\\ML\\annual-freshwater-withdrawals.csv") # Apni Water file ka naam dalein
forest_df = pd.read_csv("C:\\Users\\pawan\\Downloads\\EnvironmentProject\\ML\\annual-change-forest-area.csv") # Apni Forest file ka naam dalein
# 3. Call the functions (Note the True on the last line!)
train_and_export(co2_df, "Entity", "Year", "CO₂ emissions per capita", target_countries, future_years, "co2_predictions.json")
train_and_export(pm25_df, "Entity", "Year", "Outdoor air pollution exposure (population-weighted PM2.5)", target_countries, future_years, "pm25_predictions.json")
train_and_export(water_df, "Entity", "Year", "Annual freshwater withdrawals", target_countries, future_years, "water_predictions.json")

# allow_negative=True allows this specific model to predict negative forest change (deforestation)
train_and_export(forest_df, "Entity", "Year", "Annual change in forest area", target_countries, future_years, "forest_predictions.json", allow_negative=True)

Exported co2_predictions.json
Exported pm25_predictions.json
Exported water_predictions.json
Exported forest_predictions.json

In [38]:
df = pd.read_csv("C:\\Users\\pawan\\Downloads\\EnvironmentProject\\ML\\annual-change-forest-area.csv") 
df.head()

        Entity Code  Year  Annual change in forest area
0  Afghanistan  AFG  1991                           0.0
1  Afghanistan  AFG  1992                           0.0
2  Afghanistan  AFG  1993                           0.0
3  Afghanistan  AFG  1994                           0.0
4  Afghanistan  AFG  1995                           0.0

In [8]:
model.fit(X_train, y_train)
predictions = model.predict(X_test)
print("MAE :", mean_absolute_error(y_test, predictions))
print("R² :", r2_score(y_test, predictions))

MAE : 0.5932027277927676
R² : 0.9284209863059109

In [18]:
rmse = np.sqrt(mean_squared_error(y_test, predictions))